# Generated by Django 6.0.6 on 2026-07-01 14:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrateur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_message', models.CharField(choices=[('general', 'Message général'), ('notes', 'Notes'), ('bulletin', 'Bulletin'), ('emploi', 'Emploi du temps'), ('presence', 'Présences')], default='general', max_length=20)),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField(blank=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='messages/pdf/')),
                ('lu', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='administrateur.eleve')),
                ('expediteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='AccesEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contenu', models.CharField(choices=[('notes', 'Notes'), ('bulletin', 'Bulletin'), ('emploi', 'Emploi du temps'), ('presence', 'Présences')], max_length=20)),
                ('trimestre', models.CharField(blank=True, choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], help_text='Trimestre concerné (notes/bulletin). Vide pour emploi/présence.', max_length=2, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_activation', models.DateTimeField(auto_now_add=True)),
                ('active_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acces_accordes', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces', to='administrateur.eleve')),
            ],
            options={
                'verbose_name': 'Accès élève',
                'verbose_name_plural': 'Accès élèves',
                'unique_together': {('eleve', 'type_contenu', 'trimestre')},
            },
        ),
    ]
