# Generated by Django 6.0.6 on 2026-07-09 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reponse_a',
            field=models.ForeignKey(blank=True, help_text="Message d'origine auquel celui-ci répond (vide si c'est un message initial).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to='eleve.message'),
        ),
    ]
