# Generated by Django 6.0.6 on 2026-06-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='enseignant_principal',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='matieres',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='salle',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='classe',
        ),
        migrations.DeleteModel(
            name='Matiere',
        ),
        migrations.DeleteModel(
            name='Salle',
        ),
        migrations.DeleteModel(
            name='Classe',
        ),
        migrations.DeleteModel(
            name='Eleve',
        ),
    ]
