# Generated by Django 6.0.6 on 2026-07-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_utilisateur_options_utilisateur_photo_profil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('enseignant', 'Enseignant'), ('eleve', 'Élève'), ('secretaire', 'Secretaire'), ('parent', 'Parent')], default='eleve', max_length=20),
        ),
    ]
