# Generated by Django 6.0.6 on 2026-07-08 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0005_etablissement'),
        ('utilisateurs', '0003_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='etablissement',
            field=models.ForeignKey(blank=True, help_text="L'établissement auquel appartient ce compte.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='administrateur.etablissement'),
        ),
    ]
