# Generated by Django 6.0.6 on 2026-07-01 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrateur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentEnfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.CharField(default='Parent/Tuteur', help_text='Ex : Père, Mère, Tuteur...', max_length=50)),
                ('date_liaison', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents_lies', to='administrateur.eleve')),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='enfants_lies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lien parent / enfant',
                'verbose_name_plural': 'Liens parents / enfants',
                'unique_together': {('parent', 'eleve')},
            },
        ),
    ]
