# Generated by Django 6.0.6 on 2026-07-01 14:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrateur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraisNiveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('6eme', '6ème'), ('5eme', '5ème'), ('4eme', '4ème'), ('3eme', '3ème'), ('seconde', 'Seconde'), ('premiere', '1ère'), ('terminale', 'Terminale')], max_length=20, unique=True)),
                ('montant_inscription', models.DecimalField(decimal_places=0, default=0, help_text="Frais d'inscription pour ce niveau (FCFA).", max_digits=10)),
                ('montant_scolarite', models.DecimalField(decimal_places=0, default=0, help_text='Frais de scolarité annuelle pour ce niveau (FCFA).', max_digits=10)),
                ('annee_scolaire', models.CharField(default='2026-2027', max_length=9)),
                ('fichier_pdf', models.FileField(blank=True, help_text='Programme scolaire et informations du niveau (PDF).', null=True, upload_to='frais_niveaux/')),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Frais par niveau',
                'verbose_name_plural': 'Frais par niveau',
                'ordering': ['niveau'],
            },
        ),
        migrations.CreateModel(
            name='TranchePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex : 1ère tranche, 2ème tranche...', max_length=100)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('date_limite', models.DateField(help_text='Date limite de paiement pour cette tranche.')),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='secretaire.fraisniveau')),
            ],
            options={
                'verbose_name': 'Tranche de paiement',
                'verbose_name_plural': 'Tranches de paiement',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(default=django.utils.timezone.now, help_text='Date à laquelle le paiement a été effectué.')),
                ('paie_inscription', models.BooleanField(default=False, help_text="Ce paiement couvre-t-il les frais d'inscription ?")),
                ('montant', models.DecimalField(decimal_places=0, help_text='Montant réellement reçu pour ce paiement (FCFA).', max_digits=10)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='administrateur.eleve')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL)),
                ('tranches', models.ManyToManyField(blank=True, help_text='Tranche(s) de scolarité couvertes par ce paiement.', related_name='paiements', to='secretaire.tranchepaiement')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement', '-id'],
            },
        ),
    ]
