# Generated by Django 6.0.6 on 2026-07-01 14:47

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0003_alter_utilisateur_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('6eme', '6ème'), ('5eme', '5ème'), ('4eme', '4ème'), ('3eme', '3ème'), ('seconde', 'Seconde'), ('premiere', '1ère'), ('terminale', 'Terminale')], max_length=20)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['niveau'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('groupe', models.CharField(choices=[('scientifique', 'Matières Scientifiques'), ('litteraire', 'Matières Littéraires'), ('autre', 'Autres Matières')], default='autre', help_text='Catégorie utilisée pour regrouper les matières sur le bulletin.', max_length=20)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['nom_matiere'],
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('capacite', models.PositiveIntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CreneauHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('est_pause', models.BooleanField(default=False, help_text="Cochez pour une pause (récréation, déjeuner) : aucun cours n'y est assigné.")),
            ],
            options={
                'verbose_name': 'Créneau horaire',
                'verbose_name_plural': 'Créneaux horaires',
                'ordering': ['jour', 'heure_debut'],
                'unique_together': {('jour', 'heure_debut')},
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('nom_parent', models.CharField(max_length=150)),
                ('telephone_parent', models.CharField(max_length=20)),
                ('email_parent', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_inscription', models.DateField(default=django.utils.timezone.now)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves', to='administrateur.classe')),
                ('compte', models.OneToOneField(blank=True, help_text="Compte de connexion de l'élève (role='eleve').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleve_profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['-date_inscription', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('domaine_enseignement', models.CharField(blank=True, help_text='Ex : Sciences, Langues, Lettres...', max_length=150)),
                ('classe_principale', models.ForeignKey(blank=True, help_text='Classe dont cet enseignant est le professeur principal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants_principaux_de', to='administrateur.classe')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
            },
            bases=('utilisateurs.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='enseignant_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_dirigees', to='administrateur.enseignant'),
        ),
        migrations.CreateModel(
            name='ClasseMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=1, default=1, help_text='Coefficient utilisé pour le calcul de la moyenne pondérée.', max_digits=4, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('heures_semaine', models.DecimalField(decimal_places=1, default=1, help_text="Nombre d'heures de cours par semaine pour cette matière dans cette classe.", max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.classe')),
                ('enseignant', models.ForeignKey(blank=True, help_text='Enseignant qui dispense cette matière dans cette classe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres_enseignees', to='administrateur.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.matiere')),
            ],
            options={
                'verbose_name': 'Matière de la classe',
                'verbose_name_plural': 'Matières des classes',
                'unique_together': {('classe', 'matiere')},
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='classes', through='administrateur.ClasseMatiere', to='administrateur.matiere'),
        ),
        migrations.AddField(
            model_name='classe',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='administrateur.salle'),
        ),
        migrations.CreateModel(
            name='SemaineScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(help_text='Lundi de la semaine', unique=True)),
                ('date_fin', models.DateField(help_text='Samedi de la semaine')),
                ('cloturee', models.BooleanField(default=False)),
                ('cloturee_le', models.DateTimeField(blank=True, null=True)),
                ('cloturee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semaines_cloturees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Semaine scolaire',
                'verbose_name_plural': 'Semaines scolaires',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='BulletinVerrou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], max_length=2)),
                ('verrouille', models.BooleanField(default=False)),
                ('verrouille_le', models.DateTimeField(blank=True, null=True)),
                ('verrouille_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_verrouilles', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_verrous', to='administrateur.eleve')),
            ],
            options={
                'verbose_name': 'Verrou de bulletin',
                'verbose_name_plural': 'Verrous de bulletins',
                'unique_together': {('eleve', 'trimestre')},
            },
        ),
        migrations.CreateModel(
            name='BulletinAppreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], max_length=2)),
                ('absences_justifiees_heures', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('absences_non_justifiees_heures', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('appreciation_conseil', models.TextField(blank=True, help_text='Appréciation générale du conseil de classe pour ce trimestre.')),
                ('decision_conseil', models.CharField(blank=True, help_text="Ex : Admis(e), Travail insuffisant, Conseil d'avertissement...", max_length=100)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='administrateur.eleve')),
            ],
            options={
                'verbose_name': 'Appréciation de bulletin',
                'verbose_name_plural': 'Appréciations de bulletin',
                'unique_together': {('eleve', 'trimestre')},
            },
        ),
        migrations.CreateModel(
            name='AppelVerrouille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_verrouillage', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels_verrouilles', to='administrateur.classe')),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels_verrouilles', to='administrateur.creneauhoraire')),
                ('verrouille_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_verrouilles_par_moi', to='administrateur.enseignant')),
            ],
            options={
                'verbose_name': 'Appel verrouillé',
                'verbose_name_plural': 'Appels verrouillés',
                'unique_together': {('classe', 'creneau', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], max_length=2)),
                ('evaluation', models.CharField(choices=[('sequence1', 'Séquence 1'), ('sequence2', 'Séquence 2'), ('examen', 'Examen')], max_length=20)),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, help_text="Note sur 20. Laisser vide si l'élève n'a pas encore de note.", max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('date_saisie', models.DateTimeField(auto_now=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='administrateur.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='administrateur.matiere')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['trimestre', 'evaluation'],
                'unique_together': {('eleve', 'matiere', 'trimestre', 'evaluation')},
            },
        ),
        migrations.CreateModel(
            name='NoteVerrou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], max_length=2)),
                ('verrouille', models.BooleanField(default=False)),
                ('verrouille_le', models.DateTimeField(blank=True, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_verrous', to='administrateur.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_verrous', to='administrateur.matiere')),
                ('verrouille_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_verrouillees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verrou de notes',
                'verbose_name_plural': 'Verrous de notes',
                'unique_together': {('classe', 'matiere', 'trimestre')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'Retard')], default='present', max_length=10)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='administrateur.classe')),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='administrateur.creneauhoraire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='administrateur.eleve')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_enregistrees', to='administrateur.enseignant')),
                ('semaine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='administrateur.semainescolaire')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date'],
                'unique_together': {('eleve', 'classe', 'date', 'creneau')},
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emploi_du_temps', to='administrateur.classe')),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois', to='administrateur.creneauhoraire')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois_du_temps', to='administrateur.enseignant')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois', to='administrateur.matiere')),
                ('semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='administrateur.semainescolaire')),
            ],
            options={
                'verbose_name': "Case d'emploi du temps",
                'verbose_name_plural': 'Emploi du temps',
                'ordering': ['creneau__jour', 'creneau__heure_debut'],
                'unique_together': {('semaine', 'classe', 'creneau')},
            },
        ),
    ]
