# Generated by Django 6.0.6 on 2026-07-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0002_parentenfant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrimestrePeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], max_length=2, unique=True)),
                ('date_debut', models.DateField(help_text='Date de début du trimestre')),
                ('date_fin', models.DateField(help_text='Date de fin du trimestre')),
                ('annee', models.CharField(default='2025-2026', help_text='Année scolaire (ex: 2025-2026)', max_length=9)),
            ],
            options={
                'verbose_name': 'Période de trimestre',
                'verbose_name_plural': 'Périodes de trimestres',
                'ordering': ['trimestre'],
            },
        ),
    ]
