# Generated by Django 6.0.6 on 2026-07-03 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0003_trimestreperiode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='justifiee',
            field=models.BooleanField(default=False, help_text="Cochez si l'absence est justifiée (certificat médical, autorisation...)"),
        ),
        migrations.AlterField(
            model_name='presence',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_enregistrees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presence',
            name='semaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='administrateur.semainescolaire'),
        ),
    ]
