# Generated by Django 6.0.6 on 2026-07-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0004_presence_justifiee_alter_presence_enregistre_par_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('sigle', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='etablissement/logo/')),
                ('type_etablissement', models.CharField(choices=[('lycee', 'Lycée'), ('college', 'Collège'), ('ecole_primaire', 'École primaire'), ('bilingue', 'Établissement bilingue'), ('autre', 'Autre')], default='lycee', max_length=30)),
                ('ministere', models.CharField(choices=[('minesec', 'Ministère des Enseignements Secondaires (MINESEC)'), ('minedub', "Ministère de l'Éducation de Base (MINEDUB)"), ('minsup', "Ministère de l'Enseignement Supérieur (MINSUP)"), ('prive', 'Établissement privé (hors tutelle ministérielle directe)')], default='minesec', max_length=30)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('delegation_regionale', models.CharField(blank=True, max_length=150, null=True)),
                ('delegation_departementale', models.CharField(blank=True, max_length=150, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('boite_postale', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
            },
        ),
    ]
