# Generated by Django 6.0.6 on 2026-07-13 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0005_etablissement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emploidutemps',
            options={'verbose_name': 'Emploi du temps', 'verbose_name_plural': 'Emplois du temps'},
        ),
        migrations.AlterUniqueTogether(
            name='emploidutemps',
            unique_together={('classe', 'creneau')},
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='creneau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.creneauhoraire'),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrateur.enseignant'),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrateur.matiere'),
        ),
        migrations.RemoveField(
            model_name='emploidutemps',
            name='semaine',
        ),
    ]
