# Generated by Django 6.0.6 on 2026-07-13 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0006_alter_emploidutemps_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploiVerrou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verrouille', models.BooleanField(default=False)),
                ('verrouille_le', models.DateTimeField(blank=True, null=True)),
                ('classe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emploi_verrou', to='administrateur.classe')),
                ('verrouille_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois_verrouilles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verrou emploi du temps',
                'verbose_name_plural': 'Verrous emploi du temps',
            },
        ),
    ]
